title: Andrew Dean Davis
url: 'http://adavis46.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
style: styles-5
#style: styles-6


#Profile information
name: Andrew Dean Davis
tagline: Instructional Designer and Teacher
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: adavis46@outlook.com
phone: 770 598 4935
website: adavis46.io
linkedin: adavis46
github: adavis46
twitter: '@drewdavis278'

#Update all the sections by editing the files inside _includes folder.
